{"uuid": "01ff3c63-de45-41d2-b942-944af59bf31d", "children": ["3dd55269-69ba-441c-be6e-f9d5d5234602"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n\tGetHandleVerifier [0x00FC38B3+24035]\n\t(No symbol) [0x00F4BC44]\n\t(No symbol) [0x00E2C2D3]\n\t(No symbol) [0x00E9821C]\n\t(No symbol) [0x00E9762E]\n\t(No symbol) [0x00E98C62]\n\t(No symbol) [0x00E98B7A]\n\t(No symbol) [0x00E8FC26]\n\t(No symbol) [0x00E6218C]\n\t(No symbol) [0x00E6310D]\n\tGetHandleVerifier [0x012696D3+2800643]\n\tGetHandleVerifier [0x012C428E+3172286]\n\tGetHandleVerifier [0x012BCEA2+3142610]\n\tGetHandleVerifier [0x01066C60+692624]\n\t(No symbol) [0x00F54C5D]\n\t(No symbol) [0x00F51968]\n\t(No symbol) [0x00F51B00]\n\t(No symbol) [0x00F43FB0]\n\tBaseThreadInitThunk [0x7627FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77CE809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77CE806E+238]\n\n", "trace": "  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\Учёба все года\\Skypro\\Skypro_Diplom\\conftest.py\", line 12, in driver\n    browser = webdriver.Firefox(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 71, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\zahar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730323986720, "stop": 1730323990510}], "start": 1730323986719, "stop": 1730323990589}